### ISSUE TITLE
Position of anusvara (ં) and candrabindu (ઁ) for Gujarati letters છ and જ

### ISSUE THREAD

**Issue by vizzmay** [notofonts/gujarati#9]
- Noto Sans Gujarati, version 2.001
- Noto Serif Gujarati, version 2.001

As shown in the images, anusvara (ં) (U+0A82) and candrabindu (ઁ) (U+0A81) are positioned in the center at present. (Red outline)

- Anusvara and Candrabindu for Sans Gujarati

![cha-ja-anusvara-gujarati-sans-serif](https://user-images.githubusercontent.com/10206339/85158108-fe922900-b279-11ea-95e2-6e915fb8b445.png)

![cha-ja-candrabindu-gujarati-sans-serif](https://user-images.githubusercontent.com/10206339/85158504-1cf82480-b27a-11ea-9099-51b68f1ab17e.png)

- Anusvara and Candrabindu for Serif Gujarati

![cha-ja-anusvara-gujarati-serif](https://user-images.githubusercontent.com/10206339/85158180-0356dd00-b27a-11ea-98ff-396d918db0f0.png)

![cha-ja-candrabindu-gujarati-serif](https://user-images.githubusercontent.com/10206339/85158523-1e295180-b27a-11ea-9d41-903f19ce022f.png)

However, these signs are usually applied slightly off-center.

- For છ, the signs are placed above the loop.
- For જ, the signs are placed above the branch/stem.

See the placement of matra in છે and જે for reference.

- Sans Gujarati

![che-je-sans](https://user-images.githubusercontent.com/10206339/85159107-adcf0000-b27a-11ea-922a-71fe8aee43ce.png)

- Serif Gujarati

![che-je-serif](https://user-images.githubusercontent.com/10206339/85159112-af98c380-b27a-11ea-9456-43e72f99dfb2.png)

**Edit:**

Also applicable to repha. (ર્છ = ર + ્ + છ, ર્જ = ર + ્ + જ)

Noto Sans Gujarati

![rja-rchha-sans](https://user-images.githubusercontent.com/10206339/86160077-e0a1af80-bb28-11ea-9ed8-6c2bd204fea5.png)

Noto Serif Gujarati has appropriate positioning

![rja-rchha-serif](https://user-images.githubusercontent.com/10206339/86160136-f44d1600-bb28-11ea-8808-543f3e493720.png)

**Comment by nizarsq** [comment]
@vizzmay could you please include the characters data for the each combination in the red squares. Thanks

**Comment by vizzmay** [comment]
For Sans Gujarati:

- છં = છ + ં
- છું = છ + ુ + ં
- છૂં = છ + ૂ + ં
- છૃં = છ + ૃ + ં
- છૄં = છ + ૄ + ં
- છૢં = છ + ૢ + ં
- છૣં = છ + ૣ + ં
- જં = જ + ં
- જીં = જ + ી + ં
- જું = જ + ુ + ં
- જૂં = જ + ૂ + ં
- જૃં = જ + ૃ + ં
- જૄં = જ + ૄ + ં
- જૢં = જ + ૢ + ં
- જૣં = જ + ૣ + ં
- છઁ = છ + ઁ
- છુઁ = છ + ુ + ઁ
- છૂઁ = છ + ૂ + ઁ
- છૃઁ = છ + ૃ + ઁ
- છૄઁ = છ + ૄ + ઁ
- છૢઁ = છ + ૢ + ઁ
- છૣઁ = છ + ૣ + ઁ
- જઁ = જ + ઁ
- જીઁ = જ + ી + ઁ
- જુઁ = જ + ુ + ઁ
- જૂઁ = જ + ૂ + ઁ
- જૃઁ = જ + ૃ + ઁ
- જૄઁ = જ + ૄ + ઁ
- જૢઁ = જ + ૢ + ઁ
- જૣઁ = જ + ૣ + ઁ

For Serif Gujarati:

- Above combinations
- જાં = જ + ા + ં
- જાઁ = જ + ા + ઁ

**Comment by simoncozens** [comment]
I'm not convinced by this; it seems stylistic. First, there was obviously a deliberate decision by the designer to use centered anchors - both sans and serif use alternate anchors to place the marks in the centered position for these glyphs. Second, looking at different fonts from the same foundry (Indian Type Foundry) shows different options. Hind Varodara places it centered:
<img width="176" alt="Screenshot 2023-03-27 at 11 16 54" src="https://user-images.githubusercontent.com/106728/227913723-dd91ffc4-e09c-43b7-be0d-2ba6bdbd8196.png">

while Kumar One places it to the right:
<img width="158" alt="Screenshot 2023-03-27 at 11 17 14" src="https://user-images.githubusercontent.com/106728/227913785-5b85eebe-3d72-48f8-826b-8f88ebff0aba.png">

Meanwhile, Pooja goes for centered marks as well:
<img width="153" alt="Screenshot 2023-03-27 at 11 17 38" src="https://user-images.githubusercontent.com/106728/227913876-33d74e57-58ca-4b8a-9592-f8fa693530fb.png">
while Ek Type consistently place it on the right.

I'm inclined to treat it as a matter of stylistic preference unless we have compelling evidence otherwise.
